# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Ingrian spellchecker"
izh = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Ingrian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
izh = "TRANSLATE: A spellchecker for Ingrian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.izh"

[windows]
system_product_code = "{978EA20D-ECC0-4C5A-8D29-47F0698663B1}_is1"
legacy_product_codes = [
    { value = "5FDDEFE6-0BE4-4CD0-98EB-A063337A9789", kind = "nsis" },
    { value = "AE388B61-7415-4367-A3DE-B80AEB9DAAD7", kind = "nsis" }
]

[package.speller]
name = "Ingrian"
version = "0.1.1"

[package.grammar]
name = "Ingrian"
version = "0.1.0"

[package.tts-text-proc]
name = "Ingrian"
version = "0.1.0"

[package.hyphenator]
name = "Ingrian"
version = "0.1.0"
